steps:
  # test
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['test']
  # Copy api-schema dir to build dir
  - name: bash
    script: cp -r ./api-schema ./spino-be/api-schema
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spino-be', './spino-be']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spino-be']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'spino-be', '--image', 'gcr.io/$PROJECT_ID/spino-be', '--region', 'asia-northeast1', '--set-env-vars', 'COLLECTION_NAME=WildlifeInfo']
images:
  - gcr.io/$PROJECT_ID/spino-be