name: update-cloud-storage
on:
  push:
    branches:
      - main
    paths:
      - 'slack-config/**'
jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'slack-config'
          destination: 'spino-385712-notifiers-config'
          parent: false